name = "imperial-command"
compatibility_date = "2025-05-20"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "./build/client"

[[d1_databases]]
binding = "DB"
database_name = "imperial-command-db"
database_id = "TBD"
migrations_dir = "server/drizzle"
